language: php

php:
- '5.6'
- '7.0'
- '7.1'
- hhvm
- nightly

before_script: composer install

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

notifications:
    on_success: never
    on_failure: always